CREATE TABLE STUDENT (
    ID VARCHAR(20) PRIMARY KEY,
    PWD VARCHAR(100) NOT NULL,
    NAME VARCHAR(50) NOT NULL,
    GENDER VARCHAR(10) NOT NULL,
    BIRTH VARCHAR(15) NOT NULL,
    TEL VARCHAR(15) NOT NULL,
    ZIPCODE VARCHAR(10) NOT NULL,
    ADDR VARCHAR(200) NOT NULL,
    DETAIL_ADDR VARCHAR(200) ,
    EMAIL VARCHAR(100) NOT NULL,
    DEPARTMENT VARCHAR(50) NOT NULL,
    GRADE VARCHAR(15) NOT NULL,
    ADMISSION_DATE DATE NOT NULL,
    GRADUATION_DATE DATE NOT NULL,
    JOIN_DATE DATE NOT NULL,
    MODIFY_DATE DATE NOT NULL,
    STATUS VARCHAR(10) NOT NULL
) DEFAULT CHARSET=UTF8;

CREATE TABLE PROFESSOR (
    ID VARCHAR(20) PRIMARY KEY,
    PWD VARCHAR(100) NOT NULL,
    NAME VARCHAR(50) NOT NULL,
    GENDER VARCHAR(10) NOT NULL,
    BIRTH VARCHAR(15) NOT NULL,
    TEL VARCHAR(15) NOT NULL,
    ZIPCODE VARCHAR(10) NOT NULL,
    ADDR VARCHAR(200) NOT NULL,
    DETAIL_ADDR VARCHAR(200) ,
    EMAIL VARCHAR(100) NOT NULL,
    LESSON VARCHAR(50) NOT NULL,
    JOIN_DATE DATE NOT NULL,
    MODIFY_DATE DATE,
    STATUS VARCHAR(10) NOT NULL,
    INDATE DATE NOT NULL,
    OUTDATE DATE
) DEFAULT CHARSET=UTF8;

CREATE TABLE CLASS (
   C_NUMBER INT PRIMARY KEY AUTO_INCREMENT,
   C_NAME VARCHAR(50) NOT NULL,
   C_CREATE_DATE DATE NOT NULL,
   C_START_DATE DATE NOT NULL,
   C_END_DATE DATE NOT NULL,
   C_PROF_NAME VARCHAR(20) NOT NULL,
   C_STU_COUNT INT NOT NULL,
   C_TIME VARCHAR(15) NOT NULL,
   C_INFO VARCHAR(250) NOT NULL,
   C_TERM VARCHAR(10) NOT NULL,
   C_DAY VARCHAR(10) NOT NULL
) DEFAULT CHARSET=UTF8;

CREATE TABLE ATTEND_CLASS (
   C_NUMBER INT NOT NULL,
   ID VARCHAR(20) NOT NULL
) DEFAULT CHARSET=UTF8;

CREATE TABLE TODATE (
C_NUMBER INT NOT NULL,
ID VARCHAR(20) NOT NULL,
A_DATE DATE NOT NULL,
A_STATUS ENUM("출석", "지각", "조퇴", "결석")
) DEFAULT CHARSET=UTF8;

CREATE TABLE GRADE(
C_NUMBER INT NOT NULL,
ID VARCHAR(20) NOT NULL,
LEVEL VARCHAR(5) NOT NULL,
TEST_TYPE  VARCHAR(20) NOT NULL,
START_TIME  VARCHAR(20) NOT NULL,
END_TIME VARCHAR(20) NOT NULL,
TEST_TIME VARCHAR(20) NOT NULL
) DEFAULT CHARSET=UTF8;

CREATE TABLE TASK(
T_NUMBER INT PRIMARY KEY AUTO_INCREMENT,
C_NUMBER INT NOT NULL,
ID VARCHAR(20) NOT NULL,
TITLE VARCHAR(20) NOT NULL,
INFO VARCHAR(1000) NOT NULL,
CREATE_DATE DATE NOT NULL,
MODIFY_DATE DATE,
DEADLINE DATE NOT NULL,
T_FILE1 VARCHAR(100),
T_FILE2 VARCHAR(100),
T_FILE3 VARCHAR(100)
) DEFAULT CHARSET=UTF8;

CREATE TABLE STU_TASK(
ST_NUMBER INT AUTO_INCREMENT PRIMARY KEY,
T_NUMBER INT NOT NULL,
C_NUMBER INT NOT NULL,        
ID VARCHAR(20) NOT NULL,
ST_STATUS ENUM("진행", "마감") NOT NULL,        
ST_SUBMIT ENUM("제출", "마감") NOT NULL,
ST_SCORE INT,
ST_TOTAL_SCORE INT,        
ST_CREATE_DATE DATE NOT NULL,        
ST_MODIFY_DATE DATE,
S_FILE1 VARCHAR(100),        
S_FILE2 VARCHAR(100),        
S_FILE3 VARCHAR(100)       
) DEFAULT CHARSET=UTF8;

CREATE TABLE BOARD(
B_NUMBER INT AUTO_INCREMENT PRIMARY KEY,
B_TARGET VARCHAR(20) NOT NULL,
B_TITLE VARCHAR(20)  NOT NULL,
B_INFO VARCHAR(1000)  NOT NULL,
B_WRITER VARCHAR(20)  NOT NULL,
B_CREATE_DATE DATE  NOT NULL,
B_MODIFY_DATE DATE,        
B_VIEW INT DEFAULT 0,
B_TYPE VARCHAR(20) NOT NULL,     
B_FILE1 VARCHAR(100),        
B_FILE2 VARCHAR(100),       
B_FILE3 VARCHAR(100)           
) DEFAULT CHARSET=UTF8;

CREATE TABLE CALENDAR(
CAL_DATE TIMESTAMP NOT NULL,
CAL_EDATE TIMESTAMP,
CAL_TITLE VARCHAR(20) NOT NULL,
CAL_INFO VARCHAR(50) NOT NULL,
CAL_CREATE_DATE DATE NOT NULL,
CAL_MODIFY_DATE DATE,
CAL_WRITER VARCHAR(20) NOT NULL     
) DEFAULT CHARSET=UTF8;

CREATE TABLE NOTE(
N_NUMBER INT AUTO_INCREMENT PRIMARY KEY,
N_SENDER VARCHAR(20) NOT NULL,        
N_RECIVER VARCHAR(20) NOT NULL,        
N_TITLE VARCHAR(20) NOT NULL,
N_INFO VARCHAR(200) NOT NULL,
N_SEND_DATE DATE NOT NULL,
N_RECIVE_DATE DATE  
) DEFAULT CHARSET=UTF8;

CREATE TABLE COMMENT(
CO_NUMBER INT AUTO_INCREMENT PRIMARY KEY,
B_NUMBER INT NOT NULL,
ID VARCHAR(20) NOT NULL,        
CO_INFO VARCHAR(200) NOT NULL,
CO_CREATE_DATE DATE NOT NULL,        
CO_MODIFY_DATE DATE        
) DEFAULT CHARSET=UTF8;

